FROM python:3.12-slim

RUN apt update && \
    apt install -y postgresql-15 postgresql-client-15


WORKDIR /app

RUN pip install --upgrade pip 
 
COPY requirements.txt  /app/
 
RUN pip install --no-cache-dir -r requirements.txt
 
COPY . /app/
 
CMD ["/bin/bash", "./main.sh"]

