#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" --port 5000 <<EOSQL
CREATE USER $MLOPS_DB_USER;
GRANT $MLOPS_DB_USER to postgres;
CREATE DATABASE $MLOPS_DB_NAME;
ALTER DATABASE $MLOPS_DB_NAME OWNER TO $MLOPS_DB_USER;
GRANT USAGE, CREATE ON SCHEMA PUBLIC TO $MLOPS_DB_USER;
ALTER USER $MLOPS_DB_USER WITH PASSWORD '${MLOPS_DB_PASS}';
ALTER USER $MLOPS_DB_USER CREATEDB;
ALTER ROLE $MLOPS_DB_USER SET client_encoding TO 'utf8';
ALTER ROLE $MLOPS_DB_USER SET default_transaction_isolation TO 'read committed';
ALTER ROLE $MLOPS_DB_USER SET timezone TO 'UTC';
EOSQL


