apiVersion: v1
kind: Service
metadata:
  name: mlops-db
spec:
  selector:
    application: mlops
    app: mlops-db
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: mlops-db
      application: mlops
  serviceName: mlops-db
  template:
    metadata:
      labels:
        app: mlops-db
        application: mlops
    spec:
      serviceAccountName: postgres
      containers:
        - name: mlops-db
          image: 'postgres:15'
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mlops-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: postgres
              name: postgres-pv
            - mountPath: /docker-entrypoint-initdb.d
              name: sql-init-mount
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: sql-init-mount
          configMap:
            name: initsql
            items:
              - key: init.sh
                path: init.sh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
