apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
data:
  prometheus.yml: |
    global:
      scrape_interval:     5s
      evaluation_interval: 5s
 
    alerting:
      alertmanagers:
 
    scrape_configs:
      - job_name: 'django-app'
        static_configs:
          - targets: ['backend:8000']
            labels:
              group: 'server'


