apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization  

resources:
  - ../../base

patches:
  - path: ./backend-deployment.yaml
  - path: ./backend-service.yaml
  - path: ./nginx-deployment.yaml

components:
  - ../../components/postgresql
#  - ../../components/container-images-tag
