apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization  

resources:
  - backend.yaml
  - nginx.yaml
  - nginx-config.yaml

labels:
  - pairs:
      application: mlops
    includeSelectors: true

configMapGenerator:
  - name: mlops-config
    envs: 
      - example.env

components:
  - ../components/grafana
  - ../components/prometheus

generatorOptions:
  disableNameSuffixHash: true


