apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
      events {}
      http {
          default_type application/octet-stream;
          include mime.types;
          client_max_body_size 0;
          proxy_read_timeout 60s;
      
          server {
              location / {
                  try_files $uri $uri/ /index.html @backend;
              }
      
              location /static/admin {
                  try_files $uri @backend;
              }
      
              location /static/rest_framework {
                  try_files $uri @backend;
              }
      
              location /api {
                  try_files $uri @backend;
              }
      
              location @backend {
                  proxy_set_header X-Forwarded-Proto https;
                  proxy_set_header X-Url-Scheme $scheme;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header Host $http_host;
                  proxy_redirect off;
                  proxy_pass   http://backend:8000;
              }
      
              location /static/ {
                  autoindex on;
                  alias /app/ml_server/static/;
              }
          }
      }
      


