apiVersion: v1
kind: Service
metadata:
  name: mlops-db
spec:
  selector:
    application: mlops
    app: mlops-db
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: mlops-db
      application: mlops
  serviceName: mlops-db
  template:
    metadata:
      labels:
        app: mlops-db
        application: mlops
    spec:
      serviceAccountName: postgres
      containers:
        - name: mlops-db
          image: 'postgres:15'
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mlops-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-pv
      volumes:
        - name: db-pv
          emptyDir: {}
          #persistentVolumeClaim:
            #claimName: db-pvc
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: db
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 256Mi
#  hostPath:
#    path: /host/postgresql
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: db-pvc
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 512Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
